apax_challenge/apax_challenge/urls.py
"""apax_challenge URL Configuration

So, person doesn't really do much, but it and location get their own
namespaces. See location.urls and person.urls for more
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/',
        admin.site.urls),
    url(r'^p/',
        include('person.urls', namespace="person")),
    url(r'^l/',
        include('location.urls', namespace="location")),
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('person:home')),
        name="home"),
]

apax_challenge/location/urls.py
from django.conf.urls import url

from .views import (LocationCreate, LocationDetail, LocationRefresh,
	LocationRefreshAll, LocationRefreshJson)

urlpatterns = [
	url(r'^n[/]$',
		LocationCreate.as_view(),
		name="create"),
	url(r'^(?P<pk>\d+)[/]$',
		LocationDetail.as_view(),
		name="detail"),
	url(r'^r/(?P<pk>\d+)[/]$',
		LocationRefresh.as_view(),
		name="refresh"),
	url(r'^r/(?P<pk>\d+)/j[/]$',
		LocationRefreshJson.as_view(),
		name="ajax"),
	url(r'^$',
		LocationRefreshAll.as_view(),
		name="refresh_all"),
]

apax_challenge/person/urls.py
from django.conf.urls import url

from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from django.views.generic import TemplateView
from .views import PersonView, PersonHome, PersonCreate

urlpatterns = [
	url(r'home',
		PersonHome.as_view(),
		name='home'),
	url(r'^(?P<pk>\d+)[/]',
		PersonView.as_view(),
		name="detail"),

	url(r'^login',
		auth_views.login,
		{'template_name': 'person/login.html'},
		name='login'),
	url(r'^logout',
		auth_views.logout,
		{'next_page': reverse_lazy('person:login')},
		name='logout'),

	url(r'^create',
		PersonCreate.as_view(),
		name="create")
]

apax_challenge/person/models.py
from django.db import models
from django.contrib.auth.models import User

from location.models import Location

class Person(models.Model):
	""" Very simple person model """
	user = models.OneToOneField(User)
	location = models.ManyToManyField(Location)

	def __str__(self):
		return self.user.username

apax_challenge/person/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import DetailView, FormView
from django.views import View
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import login
from .models import Person

class PersonHome(View):
	""" Kind of a crude redirect to the login page. SHould just rewrite URLs I guess """
	def get(self, request):
		if request.user.is_authenticated:
			user = request.user.pk
			person = get_object_or_404(Person, user=user)
			return HttpResponseRedirect(reverse('person:detail', kwargs={'pk': person.pk}))
		else:
			return HttpResponseRedirect(reverse('person:login'))

class PersonView(DetailView):
	""" Shows us a person page """
	model = Person
	template_name = 'person/detail.html'

class PersonForm(forms.Form):
	""" New user and login form """
	name = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	def clean_name(self):
		""" No duplicates """
		field = self.cleaned_data['name']
		if User.objects.filter(username=field):
			raise forms.ValidationError('Name is in use')

		return field

class PersonCreate(FormView):
	""" Create a user """
	form_class = PersonForm
	template_name = "person/create.html"
	success_url = '/'

	def form_valid(self, form):
		""" Create a user and link it to a new Person"""
		username = form.cleaned_data['name']
		pw = form.cleaned_data['password']

		user = User.objects.create_user(username, password=pw)
		if user:
			login(self.request, user)

		p = Person(user=user)
		p.save()
		return super(PersonCreate, self).form_valid(form)

apax_challenge/person/templates/person/base.html
{% load bootstrap3 %}

<!-- Basic layout for overrides.
	Defines empty title, body, and script blocks. These can (and should) be
	overridden by the various templates
  -->

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

{% bootstrap_css %}
{% bootstrap_javascript %}

<html>
<head>
</head>
<body>

{% bootstrap_messages %}

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>
			{% block title %}

			{% endblock title %}
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2">
			<ul class="nav flex-column">
				<li class="nav-item disabled">
					<a href="#">
					{% if user.is_authenticated %}
					Signed in as {{ user.username }}
					{% else %}
					Not signed in
					{% endif %}
					</a>
				</li>
				<li class="nav-item">
					{% if user.is_authenticated %}
					<a href="/">My Locations</a>
					{% else %}
					<a class="nav-link" href="{% url 'person:login' %}">Login</a>
					{% endif %}
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'location:create' %}">New Location</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'person:create' %}">New User</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'person:logout' %}">Logout</a>
				</li>
			</ul>
		</div>
		<div class="col-md-8">
			{% block body %}
			Content!
			{% endblock body %}
		</div>
		<div class="col-md-2">

		</div>
	</div>
</div>

</body>

{% block script %}
<script>
</script>
{% endblock %}
</html>

apax_challenge/person/templates/person/create.html
{% extends "person/base.html" %}


{% block title %}
Signup!
{% endblock %}

{% block body %}

<h3>Create User</h3>

<!-- Get the shared for for username/password -->
{% include "person/login_form.html" %}


{% endblock body %}

apax_challenge/person/templates/person/detail.html
{% extends "person/base.html" %}


{% block script %}
<script type="text/javascript">

/* Create a callback function for the 'refresh' links
 * we'll also use this for refreshing everything */
function refreshLinkCallbackFactory(jqobj) {
	return function (e) {
		e.preventDefault()

		$.ajax({
			url: "/l/r/" + jqobj.attr('id') + "/j/"
		}).done(function (data, status) {
			var obj = jqobj
			var row = obj.parents(".weather-table-row")
			row.children('.hightemp-col')
				.html(data['high'])
			row.children('.lowtemp-col')
				.html(data['low'])
			row.children('.fore-col')
				.html(data['short_forecast'])
			row.children('.lastup-col')
				.html(data['last_update'])
		}).fail(function (){
			alert("Api Call Failed")
		})
	}
}

/* refreshAll by just grabbing the callback and calling it for each function.
 * This function (or the AJAX JSon generator) actually contains a bug in that
 * the date it formatted wrong, but it gives a nice visual indication of the
 * update
 */
function refreshAll(e) {
	$('.ajax_link').each(function(idx) {
		f = refreshLinkCallbackFactory($(this))
		f(e)
	})
}

/* Document ready */
$(function() {
	$('.ajax_link').each(function (idx) {
		$(this).on('click', refreshLinkCallbackFactory($(this)))
	})

	$('#refresh-all').on('click', refreshAll)
})
</script>
{% endblock %}

{% block title %}Locations for {{ person.user.username }}{% endblock %}

{% block body %}
<h3>
{{ person.user.username }}
</h3>

<table class="table table-striped">
<tr>
	<th>Location</th>
	<th>High</th>
	<th>Low</th>
	<th>Descriptive</th>
	<th>Last Updated</th>
	<th></th>
</tr>

{% for loc in person.location.all %}
<tr class="weather-table-row">
	<td>
		<a href="{% url 'location:detail' loc.pk %}">
		{{ loc.city }}, {{ loc.state }} {{ loc.zipcode }}
		</a>
	</td>
	<td class="hightemp-col">
		{{ loc.high }}
	</td>
	<td class="lowtemp-col">
		{{ loc.low }}
	</td>
	<td class="fore-col">
		{{ loc.short_forecast }}
	</td>
	<td class="lastup-col">
		{{ loc.last_update }}
	</td>
	<td>
		<!-- Refresh links are bogus now since the JS replaces them, but if you turn off
		JS this should fallback I guess -->
		<a id="{{loc.pk}}" class="ajax_link" href="{% url 'location:refresh' loc.pk %}"><span class="glyphicon glyphicon-refresh"></span></a>
	</td>
</tr>

{% endfor %}
</table>

<a id="refresh-all" href="{% url 'location:refresh_all' %}"><span class="glyphicon glyphicon-refresh"></span> Refresh All</a>

{% endblock %}

apax_challenge/person/templates/person/login.html
{% extends "person/base.html" %}

{% block title %}
User Login
{% endblock %}

{% block body %}

<h3>Login</h3>

<!-- Get the shared form for username/password -->
{% include "person/login_form.html" %}

{% endblock body %}

apax_challenge/person/templates/person/login_form.html
{% load bootstrap3 %}

<form method="post" >
{% csrf_token %}

{% bootstrap_form form %}

<input type="submit" class="btn" name="submit" value="submit"/>

</form>